// Generated by uniffi-bindgen-react-native
import installer from './NativeFerrostar';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/ferrostar';

// Now import the bindings so we can:
// - initialize them
// - export them as namespaced objects as the default export.
import * as ferrostar from './generated/ferrostar';

// Initialize the generated bindings: mostly checksums, but also callbacks.
ferrostar.default.initialize();

// Export the crates as individually namespaced objects.
export default {
  ferrostar,
};

export * from './core';
export * from './views';
