#!/bin/bash

if which swiftformat >/dev/null; then
	./.githooks/git-format-staged --formatter "swiftformat stdin --stdinpath '{}'" "apple/*.swift"
else
	echo "error: SwiftFormat not installed"
	echo "error: Install it via 'brew install swiftformat'"
	echo "error: or download from https://github.com/nicklockwood/SwiftFormat"
	exit 1
fi