version: 2
updates:
  - package-ecosystem: cargo
    directory: /common
    schedule:
      interval: monthly
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "@stadiamaps/ferrostar"
        # This is a local path dependency (wasm-pack build artifact),
        # not a published npm package.
