name: Rust (Common)
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-msrv
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-hack
      - run: just check-msrv

  semver-checks:
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-semver
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: common/Cargo.toml
          feature-group: default-features

  rustfmt:
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-rustfmt
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: rustfmt checks
        run: just format-common --check

  build:
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: just,nextest
      - name: Cargo Build
        run: just build-common --verbose
      - name: Run tests (nextest + doctests)
        run: just test-common
