name: WASM (JS)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-wasm-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - run: npm ci
        working-directory: web
          
      - run: npm run format:check
        working-directory: web

      - run: npm run build
        working-directory: web

      - name: WASM unit tests
        run: wasm-pack test --firefox --headless ferrostar --no-default-features --features wasm_js
        working-directory: common
