name: WASM (JS)
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-wasm-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: npm ci
        run: npm ci
        working-directory: web

      - name: Format + lint check
        run: just format-web --check

      - name: Build web library
        run: just build-web

      - name: Build site
        run: npm run build:site
        working-directory: web

      - name: WASM unit tests
        run: wasm-pack test --firefox --headless ferrostar --no-default-features --features wasm_js
        working-directory: common
